# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pay' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'AFNetworking'
    pod 'WechatOpenSDK'
    pod 'AliPay'
    
  # Pods for pay

  target 'payTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'payUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
